### ISSUE TITLE
Add references to articles of algorithms used

### ISSUE THREAD

**Issue by martinmaxk** [iShapeUnity/Triangulation#1]
It is stated this implementation is based on "Triangulation of monotone polygons", but I was unable to find an article of that name and also there must be an extra step before this of converting polygons to monotone pieces.

What algorithm is used in TriangulationExt.cs?

**Comment by NailxSharipov** [comment]
It's very common implementation. You can look on it in [wiki](https://en.wikipedia.org/wiki/Polygon_triangulation#Monotone_polygon_triangulation) or the first [link](http://homepages.math.uic.edu/~jan/mcs481/triangulating.pdf) in google give me a nice pdf article.

First step is break your path into this monotone-polygons that was **iShape.Triangulation.Shape.LayoutExt.public static MonotoneLayout Split(this PlainShape shape, long maxEdge, NativeArray<IntVector> extraPoints, Allocator allocator)** do!

about TriangulationExt 
**public static NativeArray<int> Triangulate(this PlainShape shape, NativeArray<IntVector> extraPoints, Allocator allocator)**
exactly implement monotone algorithm
first raw: **var layout = shape.Split(0, extraPoints, Allocator.Temp);** - break a path into monotone layout and after triangulate its
