### ISSUE TITLE
Disposing of layout.

### ISSUE THREAD

**Issue by PavelTorgashov** [iShapeUnity/Triangulation#2]
https://github.com/iShapeUnity/Triangulation/blob/d04f2c7d2bf8e9ced4177a41fa7eb55223079b9d/Runtime/iShape/Triangulation/Shape/Delaunay/Triangulation.cs#L74

Looks like you can not dispose this here. It used below in code.

**Comment by NailxSharipov** [comment]
Yes you right! Don't know why it still not fixed. Will do it on this week

**Comment by NailxSharipov** [comment]
Done! I also create project https://github.com/iShapeUnity/TriangulationDebug with tests and some test scene
