### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by murphkev** [iShapeUnity/Triangulation#6]
Heya, 

Looks like you forgot to dispose triangles in Triangulation.cs line 68

Triangles are passed into Delaunnay (lines 77 and 84); but the Delaunnay constructor copies the native array, so they never get disposed.

https://github.com/iShapeUnity/Triangulation/blob/master/Runtime/iShape/Triangulation/Shape/Delaunay/Triangulation.cs

Cheers - great package btw!

**Comment by NailxSharipov** [comment]
Heya,

Thanks for the heads-up, I agree, it's a leak!
Would you be interested in suggesting a fix or submitting a PR?
I will appreciate it.

**Comment by NailxSharipov** [comment]
fixed in 0.0.7
